import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { DarkThemeToggle, Flowbite } from "flowbite-react";
import { customTheme } from "@/components/Theme/configuration";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Flowbite  theme={{ theme: customTheme }}>
        <DarkThemeToggle hidden defaultValue={"light"}/>
          {children}</Flowbite>
      </body>
    </html>
  );
}
